config/routes.rb
Rails.application.routes.draw do

  get 'testfile/home'

  root to: "posts#index"

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  #get 'post/new', to: 'posts#new'
  #post 'post', to: 'post#create'

resources :posts, only: [:destroy, :index, :show, :new, :create, :edit, :update]
#resources: model_name_in_plural_form i.e posts and not post

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/view_counter.rb
class ViewCounter < ApplicationRecord


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController



  def home
  @counter= ViewCounter.find_by(page_name: 'home')
    if @counter ==nil
    @counter = ViewCounter.new
    @counter.page_name = 'home'
    @counter.count =1
    @counter.save

    else
    @counter.count  += 1
    @counter.save
    end
  end

  def about
    @counter = ViewCounter.find_by(page_name: 'about')

    if @counter ==nil
      @counter= ViewCounter.create(page_name: 'about', count: 1)



    else
      @counter.count  += 1
      @counter.save
    end
  end

  def contact
    @counter = ViewCounter.find_by(page_name: 'contact')


    if @counter ==nil
      @counter= ViewCounter.create(page_name: 'contact', count: 1)
      @counter.save



    else
      @counter.count  += 1
      @counter.save
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @post = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    post_params = params[:post].permit(:title, :author, :content )
    post= Post.create(post_params)
    redirect_to post_path(id: post.id)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post_params = params[:post].permit(:title, :author, :content )
    post= Post.find(params[:id])
    Post.update(post_params)
    redirect_to post_path(id: post.id)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path


    end
  end

app/controllers/testfile_controller.rb
class TestfileController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/testfile_helper.rb
module TestfileHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphacampBlogApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class= 'container'>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> About1</h1>


<%= link_to "home",root_path %>

<p>
<%= "#{@counter.count} views" %>
</p>

app/views/pages/contact.html.erb
<h1>contact page</h1>

<%= link_to "home",root_path %>

<p>
<%= "#{@counter.count} views" %>
</p>

app/views/pages/home.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-xs-4 col-xs-offset-4'>



<h1>Hello World</h1>

<p>
<%= "#{@counter.count} views" %>
</p>

<!--@counter is the same as  ViewCounter.find_by(page_name:'about').count-->

<%= 2+3 %>


<%= link_to "about",about_path %>
<%= link_to "contact",contact_path %>

app/views/posts/edit.html.erb
<%= form_for @post, url: post_path(id: @post.id), method: :put do |f| %>
<div>
  <%=f.label :title%></br>
<%= f.text_field :title %>
</div>

<div>
  <%=f.label :author%></br>
<%= f.text_field :author %>
</div>

<div>
  <%=f.label :content%></br>
<%= f.text_area :content %>
</div>

<div>

<%= f.submit "Create" %>
</div>


<div>
<%= f.submit "Destroy" %>

</div>
<% end %>

app/views/posts/index.html.erb
<table class="table">

  <thead>
    <th>Title</th>
    <th> Author </th>
  </thead>
<div class="container">
  <tbody>
    <% @post.each do |post| %>
    <tr>
      <td>
        <%= post.title %>
      </td>

      <td>

        <%= post.author %>
      </td>

      <td>
        <%= link_to 'View', post_path(id: post.id) %>
      </td>

      <td>
        <%= link_to 'Delete', post_path(id: post.id), method: :delete %>
      </td>
    </tr>

    <%end%>

  </body>
</div>


  </table>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
  <script src="../../dist/js/bootstrap.min.js"></script>
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>





<%= link_to 'Create New Post', new_post_path %>

app/views/posts/new.html.erb
<%= form_for @post, url: posts_path, method: :post do |f| %>

<div>
  <%=f.label :title%> </br>
<%= f.text_field :title %>
</div>

<div>
  <%=f.label :author%></br>
<%= f.text_field :author %>
</div>

<div>
  <%=f.label :content%></br>
<%= f.text_area :content %>
</div>

<div>

<%= f.submit "Create" %>
</div>

<div>
<%= f.submit "Destroy" %>

</div>

<% end %>

app/views/posts/show.html.erb
<h1> Post Details</h1>

<h2> <%= @post.title%> </h2>

<p> by <%=@post.author%> </p>

<p> <%=@post.content%> </p>

<%= link_to 'edit', edit_post_path(id: @post.id) %>

app/views/testfile/home.html.erb
<h1>Testfile#home</h1>

<p>oh yeah!</p>




<a href="http://google.com">google </a>

<%= form_for @post, url: post_path(id: @post.id), method: :put do |f| %>
<div>
  <%=f.label :title%>
<%= f.text_field :title %>
</div>

<div>
  <%=f.label :author%>
<%= f.text_field :author %>
</div>

<div>
  <%=f.label :content%>
<%= f.text_area :content %>
</div>

<div>

<%= f.submit "Create" %>
</div>


<div>
<%= f.submit "Destroy" %>

</div>
<% end %>